### ISSUE TITLE
Problem with compiling,

### ISSUE THREAD

**Issue by djkluesner** [rfrht/Yaesu-OLED-TX-Timer#1]

**Comment by djkluesner** [comment]
Greetings,
When I upload this to my arduino, it is checking it first and is giving me an error on line 11, with the adafruit line,
Is that because its not hooked up yet or a different display ? Im not that good at programming but would like to use this
program, I would think I may have to put my own code in there, according to what display I use ?
Dave

**Comment by rfrht** [comment]
Hello David-

Did you managed to import the **display libraries** to your Arduino IDE?

**Comment by djkluesner** [comment]
No I didnt import anything, just tried to upload  your code to it, do I have to upload libraries also ?
Thanks so much for helping and for the program.
Dave

**Comment by rfrht** [comment]
Hi David - please check this Video:

 https://youtu.be/Srb6aqnZbME 

You will have to add the `Adafruit SSD1306` and `Adafruit GFX` libraries.

And - unless you have resolved this issue, **do not close the issue** - select **Comment** instead.

**Comment by djkluesner** [comment]
OK, thanks, its been a while since I used my arduino, I need to re-educate myself on the arduino, I see at the beginning
of the program it lists the libraries needed, but when I search for wire, their is a bunch of them, I found the adafruit libraries,
I think I will figure it out, thanks so much, I did hit comment but it said I couldn't comment at this time, so I hit close, this
is all new to me also, sorry.
Dave

**Comment by rfrht** [comment]
Nothing to apologize

Please let me know how that goes! And thanks for giving the project a try!

**Comment by djkluesner** [comment]
OK, thank you, and thanks for this project !!! 
Dave KD0PXV

**Comment by rfrht** [comment]
Hello @djkluesner any progress over there?

**Comment by djkluesner** [comment]
Hi
I have a different lcd so I have to figure it out,
I have to use the crystal library. I am working on it. I got the backlight
to work so far, thanks.
Dave KD0PXV

**Comment by rfrht** [comment]
Closing it.
